name: Java CI with Maven & JaCoCo

on:
  push:
    # AQUÍ ESTÁ EL TRUCO: Agregamos 'old' para que funcione en esta rama
    branches: [ "main", "master", "old" ]
  pull_request:
    branches: [ "main", "master", "old" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Ejecutar Pruebas y Generar Reporte JaCoCo
        run: mvn clean test jacoco:report

      - name: Cargar Reporte de Cobertura como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          retention-days: 5